use_frameworks!

platform :ios, '13.0'

target 'SubstrateClientSwift_Example' do
  pod 'SubstrateClientSwift', :path => '../'
  pod 'ScaleCodecSwift', :git => 'https://github.com/sublabdev/scale-codec-swift', :commit => '7837157a0277c6da9553512d68d463a4766c41d9'
  pod 'CommonSwift', :git => 'https://github.com/sublabdev/common-swift.git', :commit => '8186f9973bc43039ddd531c839fd718e81e3b243'
  pod 'HashingSwift', :git => 'https://github.com/sublabdev/hashing-swift.git', :commit => '0a4fa228ae0cba5f63a2695fd51c966c02cfb278'

  target 'SubstrateClientSwift_Tests' do
    inherit! :search_paths
    
  end
end
